__Import Data__


In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Customer-Churn.csv')

In [3]:
data.shape
data.head()

Maior65Anos Conjuge Dependentes  MesesDeContrato TelefoneFixo  \
0            0     Sim         Nao                1          Nao   
1            0     Nao         Nao               34          Sim   
2            0     Nao         Nao                2          Sim   
3            0     Nao         Nao               45          Nao   
4            0     Nao         Nao                2          Sim   

  VariasLinhasTelefonicas ServicoDeInternet SegurancaOnline BackupOnline  \
0    SemServicoTelefonico               DSL             Nao          Sim   
1                     Nao               DSL             Sim          Nao   
2                     Nao               DSL             Sim          Sim   
3    SemServicoTelefonico               DSL             Sim          Nao   
4                     Nao       FibraOptica             Nao          Nao   

  SeguroNoDispositivo SuporteTecnico TVaCabo StreamingDeFilmes TipoDeContrato  \
0                 Nao            Nao     Nao               Nao    Mensalmente   
1                 Sim            Nao     Nao               Nao          UmAno   
2                 Nao            Nao     Nao               Nao    Mensalmente   
3                 Sim            Sim     Nao               Nao          UmAno   
4                 Nao            Nao     Nao               Nao    Mensalmente   

  PagamentoOnline FormaDePagamento  ContaMensal Churn  
0             Sim    ChequeDigital        29.85   Nao  
1             Nao      ChequePapel        56.95   Nao  
2             Sim      ChequePapel        53.85   Sim  
3             Nao    DebitoEmConta        42.30   Nao  
4             Sim    ChequeDigital        70.70   Sim

In [4]:
translate_dictionary = {'Sim': 1, 'Nao': 0}

n_data = data[['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn']]. replace(translate_dictionary)
n_data.head()


Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0        1            0             0                1      0
1        0            0             1                0      0
2        0            0             1                1      1
3        0            0             0                0      0
4        0            0             1                1      1

In [5]:
data_dummie = pd.get_dummies(data.drop(['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn'], axis=1))
final_data = pd.concat([n_data, data_dummie], axis=1)

In [6]:
final_data.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                            0   
1               34        56.95                            1   
2                2        53.85                            1   
3               45        42.30                            0   
4                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  ...  StreamingDeFilmes_Nao  \
0                                             1  ...                      1   
1                                             0  ...                      1   
2                                             0  ...                      1   
3                                             1  ...                      1   
4                                             0  ...                      1   

   StreamingDeFilmes_SemServicoDeInternet  StreamingDeFilmes_Sim  \
0                                       0                      0   
1                                       0                      0   
2                                       0                      0   
3                                       0                      0   
4                                       0                      0   

   TipoDeContrato_DoisAnos  TipoDeContrato_Mensalmente  TipoDeContrato_UmAno  \
0                        0                           1                     0   
1                        0                           0                     1   
2                        0                           1                     0   
3                        0                           0                     1   
4                        0                           1                     0   

   FormaDePagamento_CartaoDeCredito  FormaDePagamento_ChequeDigital  \
0                                 0                               1   
1                                 0                               0   
2                                 0                               0   
3                                 0                               0   
4                                 0                               1   

   FormaDePagamento_ChequePapel  FormaDePagamento_DebitoEmConta  
0                             0                               0  
1                             1                               0  
2                             1                               0  
3                             0                               1  
4                             0                               0  

[5 rows x 39 columns]

In [7]:
final_data.shape

(7043, 39)

In [8]:
pd.set_option('display.max_columns', 39)
final_data.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                            0   
1               34        56.95                            1   
2                2        53.85                            1   
3               45        42.30                            0   
4                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  VariasLinhasTelefonicas_Sim  \
0                                             1                            0   
1                                             0                            0   
2                                             0                            0   
3                                             1                            0   
4                                             0                            0   

   ServicoDeInternet_DSL  ServicoDeInternet_FibraOptica  \
0                      1                              0   
1                      1                              0   
2                      1                              0   
3                      1                              0   
4                      0                              1   

   ServicoDeInternet_Nao  SegurancaOnline_Nao  \
0                      0                    1   
1                      0                    0   
2                      0                    0   
3                      0                    0   
4                      0                    1   

   SegurancaOnline_SemServicoDeInternet  SegurancaOnline_Sim  \
0                                     0                    0   
1                                     0                    1   
2                                     0                    1   
3                                     0                    1   
4                                     0                    0   

   BackupOnline_Nao  BackupOnline_SemServicoDeInternet  BackupOnline_Sim  \
0                 0                                  0                 1   
1                 1                                  0                 0   
2                 0                                  0                 1   
3                 1                                  0                 0   
4                 1                                  0                 0   

   SeguroNoDispositivo_Nao  SeguroNoDispositivo_SemServicoDeInternet  \
0                        1                                         0   
1                        0                                         0   
2                        1                                         0   
3                        0                                         0   
4                        1                                         0   

   SeguroNoDispositivo_Sim  SuporteTecnico_Nao  \
0                        0                   1   
1                        1                   1   
2                        0                   1   
3                        1                   0   
4                        0                   1   

   SuporteTecnico_SemServicoDeInternet  SuporteTecnico_Sim  TVaCabo_Nao  \
0                                    0                   0            1   
1                                    0                   0            1   
2                                    0                   0            1   
3                                    0                   1            1   
4                                    0                   0         

In [9]:
x_mary = [[0,0,1,1,0,0,39.90,1,0,0,0,1,0,1,0,0,0,0,1,1,1,0,0,1,1,0,0,0,1,0,0,1,0,0,0,1,0,1]]

In [10]:
x = final_data.drop('Churn', axis=1)
y = final_data['Churn']

__IMPORTANT__: 
    - Swipe All values to the same scale!


In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
norm = StandardScaler()

norm_x = norm.fit_transform(x)
norm_x

array([[ 1.03453023, -0.65401193, -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       ...,
       [ 1.03453023,  1.5290241 , -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [ 1.03453023, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
        -0.54480692,  1.88720123]])

In [13]:
norm_x[0]

array([ 1.03453023, -0.65401193, -3.05401039,  0.8297975 , -0.43991649,
       -1.27744458, -1.16032292, -0.96332984,  3.05401039, -0.85417615,
        1.38171215, -0.88565976, -0.52592737,  1.00669571, -0.52592737,
       -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
       -0.52592737, -0.72396752,  1.0138687 , -0.52592737, -0.63943864,
        1.2273572 , -0.52592737, -0.79013171,  1.23648892, -0.52592737,
       -0.79607014, -0.56297505,  0.90418382, -0.51424938, -0.52504733,
        1.40641839, -0.54480692, -0.5298852 ])

In [14]:
x_mary_norm = norm.transform(pd.DataFrame(x_mary, columns=x.columns))
x_mary_norm

array([[-0.96662231, -0.65401193,  0.32743831,  0.8297975 , -0.43991649,
        -1.31816495, -0.82630172,  1.03806605, -0.32743831, -0.85417615,
        -0.72373975,  1.12910177, -0.52592737,  1.00669571, -0.52592737,
        -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
         1.90140322, -0.72396752, -0.98632101,  1.90140322,  1.56387171,
        -0.81475874, -0.52592737, -0.79013171,  1.23648892, -0.52592737,
        -0.79607014,  1.77627764, -1.1059698 , -0.51424938, -0.52504733,
         1.40641839, -0.54480692,  1.88720123]])

In [15]:
import numpy as np
a = x_mary_norm
b = norm_x[0]

- First We substract

In [16]:
a - b

array([[-2.00115254,  0.        ,  3.3814487 ,  0.        ,  0.        ,
        -0.04072036,  0.3340212 ,  2.00139589, -3.3814487 ,  0.        ,
        -2.10545189,  2.01476153,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         2.42733059,  0.        , -2.00018971,  2.42733059,  2.20331035,
        -2.04211593,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  2.33925269, -2.01015362,  0.        ,  0.        ,
         0.        ,  0.        ,  2.41708643]])

- then we will do the exponentiation

In [17]:
np.square(a-b)

array([[4.00461149e+00, 0.00000000e+00, 1.14341953e+01, 0.00000000e+00,
        0.00000000e+00, 1.65814802e-03, 1.11570160e-01, 4.00558550e+00,
        1.14341953e+01, 0.00000000e+00, 4.43292768e+00, 4.05926401e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        5.89193381e+00, 0.00000000e+00, 4.00075888e+00, 5.89193381e+00,
        4.85457649e+00, 4.17023749e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 5.47210315e+00,
        4.04071758e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 5.84230682e+00]])

- the sum

In [18]:
np.sum(np.square(a-b))

79.64857565351807

- remove the root to get the distance

In [19]:
np.sqrt(np.sum(np.square(a-b)))

8.92460506989066

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_treino, X_teste, y_treino, t_teste = train_test_split(norm_x, y, test_size=0.3, random_state=123)

__Test and Train__

- lib to create a model of ml

In [22]:
from sklearn.neighbors import KNeighborsClassifier

- instance the mode (create the model) - from default have 5 neighborshood.

In [23]:
knn = KNeighborsClassifier(metric='euclidean')

- training model with data train

In [24]:
knn.fit(x_treino, y_treino)

KNeighborsClassifier(metric='euclidean')

In [25]:
predict_knn = knn.predict(X_teste)

/Users/raphaeltorquato/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [26]:
predict_knn

array([1, 0, 0, ..., 0, 0, 0])

In [27]:
x_treino

array([[-0.96662231, -0.65401193, -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231,  1.5290241 ,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       ...,
       [ 1.03453023,  1.5290241 ,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [ 1.03453023,  1.5290241 , -3.05401039, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ]])

In [28]:
y_treino

1479    0
2377    0
6613    0
6468    0
2668    1
       ..
5218    0
4060    0
1346    1
3454    0
3582    0
Name: Churn, Length: 4930, dtype: int64

In [29]:
np.median(x_treino)

-0.5259273725834717

In [30]:
from sklearn.naive_bayes import BernoulliNB

In [31]:
bnb = BernoulliNB(binarize=0.52)

In [32]:
bnb.fit(x_treino, y_treino)

BernoulliNB(binarize=0.52)

In [33]:
predict_bnb = bnb.predict(X_teste)

In [34]:
predict_bnb

array([1, 0, 0, ..., 0, 1, 0])

In [35]:
from sklearn.tree import DecisionTreeClassifier

__Instance The Model:__

In [36]:
dtc = DecisionTreeClassifier(criterion='entropy', random_state=42)

In [37]:
dtc.fit(x_treino, y_treino)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [38]:
dtc.feature_importances_

array([0.03168742, 0.01862901, 0.00064085, 0.02675693, 0.0208788 ,
       0.2056003 , 0.29546501, 0.0061786 , 0.00273035, 0.00747536,
       0.        , 0.04908356, 0.        , 0.01609395, 0.        ,
       0.00722833, 0.01220706, 0.        , 0.01248286, 0.01138295,
       0.0006673 , 0.0095669 , 0.01841631, 0.        , 0.00650511,
       0.00385849, 0.        , 0.00666929, 0.00517146, 0.        ,
       0.00665371, 0.00473251, 0.15803541, 0.00348686, 0.01414378,
       0.01601964, 0.01064163, 0.01091026])

In [39]:
predict_deciton_tree = dtc.predict(X_teste)

In [40]:
predict_deciton_tree

array([1, 0, 0, ..., 1, 0, 0])

In [41]:
from sklearn.metrics import confusion_matrix

In [42]:
print(confusion_matrix(t_teste, predict_knn))

[[1302  221]
 [ 317  273]]


In [43]:
print(confusion_matrix(t_teste, predict_bnb))

[[1058  465]
 [ 120  470]]


In [44]:
print(confusion_matrix(t_teste, predict_deciton_tree))

[[1249  274]
 [ 290  300]]


__Accuracy__:

In [45]:
from sklearn.metrics import accuracy_score

In [46]:
print(accuracy_score(t_teste, predict_knn))

0.7453857075248462


In [47]:
print(accuracy_score(t_teste, predict_bnb))

0.7231424514907714


In [48]:
print(accuracy_score(t_teste, predict_deciton_tree))

0.7330809275911027


__Precision__:

In [49]:
from sklearn.metrics import precision_score

In [50]:
print(precision_score(t_teste, predict_knn))

0.5526315789473685


In [51]:
print(precision_score(t_teste, predict_bnb))

0.5026737967914439


In [52]:
print(precision_score(t_teste, predict_deciton_tree))

0.5226480836236934


__Recall__:

In [53]:
from sklearn.metrics import recall_score

In [54]:
print(recall_score(t_teste, predict_knn))

0.46271186440677964


In [55]:
print(recall_score(t_teste, predict_bnb))

0.7966101694915254


In [56]:
print(recall_score(t_teste, predict_deciton_tree))

0.5084745762711864


__choicing the best model__:

- Precision

In [57]:
print('KNN Model:', precision_score(t_teste,predict_knn))
print('Bernoui de Naive Bayes Model:', precision_score(t_teste,predict_bnb))
print('Decision Tree Model:', precision_score(t_teste,predict_deciton_tree))

KNN Model: 0.5526315789473685
Bernoui de Naive Bayes Model: 0.5026737967914439
Decision Tree Model: 0.5226480836236934
